#server:
#  port: 8080

spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:http://localhost:8088"

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/




